SET SERVEROUTPUT ON;

DECLARE
V_RM NUMBER(10) :=1;
V_NOME VARCHAR2 (100);
V_QTD_ALUNO NUMBER(10) := 3;
BEGIN
LOOP
--<INSTRUÇÕES>
SELECT NOME INTO V_NOME FROM ALUNO WHERE RM= V_RM;
DBMS_OUTPUT.PUT_LINE(V_NOME);
V_RM := V_RM+1;
EXIT WHEN V_RM > V_QTD_ALUNO;
END LOOP;

END;
